@EvDb.Sample.Auctions_HostAddress = http://localhost:5176


POST {{EvDb.Sample.Auctions_HostAddress}}/Auctions/create-auction
Accept: application/json
Content-Type: application/json

{
  "auctionId": 67,
  "productName": "Bike",
  "startingPrice": 400
}

###

POST {{EvDb.Sample.Auctions_HostAddress}}/Auctions/place-bid
Accept: application/json
Content-Type: application/json

{
  "auctionId": 67,
  "userId": 3,
  "bid": 300
}

###

POST {{EvDb.Sample.Auctions_HostAddress}}/Auctions/place-bid
Accept: application/json
Content-Type: application/json

{
  "auctionId": 67,
  "userId": 6,
  "bid": 450
}

###

GET {{EvDb.Sample.Auctions_HostAddress}}/Auctions/open-auctions
Accept: application/json

###